apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeapps.inhouse.com
spec:
  group: inhouse.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer

  scope: Namespaced
  names:
    plural: nodeapps
    singular: nodeapp
    kind: NodeApp
    shortNames:
      - na
