apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
